#!/usr/bin/env bash
# Every command run for the DeepSeek re-bench 20260902T202935Z, verbatim, in order. cwd = repo root unless noted.
# Serve was already running (user's, up ~32h on both Sparks); user authorised benching it in place after a defaults check.
~/projects/ai-lab/forge/gpu/lease.sh acquire pair --ttl 3h --unit rebench-deepseek
UTC=20260902T202935Z
mkdir -p evidence/rebench-$UTC
docker inspect dsv4-flash-vision-exp > evidence/rebench-$UTC/inspect-rank0.json
ssh -o BatchMode=yes spark2 docker inspect dsv4-flash-vision-exp > evidence/rebench-$UTC/inspect-rank1.json
docker image inspect dsv4-flash-vision-sm121 > evidence/rebench-$UTC/image-rank0.json
ssh -o BatchMode=yes spark2 docker image inspect dsv4-flash-vision-sm121 > evidence/rebench-$UTC/image-rank1.json
# serve-config-check.md generated by a python one-off from the inspect JSON + recipe.yaml serve.env (see file)
(cd docker && find plugin/dsv4_vision plugin/pyproject.toml patch_dspark_skip_bias_vl.py Dockerfile.b12x-vision -type f ! -name '*.pyc' ! -path '*__pycache__*' | sort | xargs sha256sum) > evidence/rebench-$UTC/docker-tree-repo.sha256
docker exec dsv4-flash-vision-exp sh -c 'cd /opt/dsv4_vision_src && find dsv4_vision pyproject.toml -type f ! -name "*.pyc" ! -path "*__pycache__*" ! -path "*.egg-info*" ! -path "*/build/*" | sort | xargs sha256sum; sha256sum /tmp/patch_dspark_skip_bias_vl.py' > evidence/rebench-$UTC/docker-tree-rank0.sha256
ssh -o BatchMode=yes spark2 "docker exec dsv4-flash-vision-exp sh -c 'cd /opt/dsv4_vision_src && find dsv4_vision pyproject.toml -type f ! -name \"*.pyc\" ! -path \"*__pycache__*\" ! -path \"*.egg-info*\" ! -path \"*/build/*\" | sort | xargs sha256sum; sha256sum /tmp/patch_dspark_skip_bias_vl.py'" > evidence/rebench-$UTC/docker-tree-rank1.sha256
# image-drift.diff: diff -u <container file via docker exec cat> docker/plugin/dsv4_vision/<file> for each differing file
curl -sf http://127.0.0.1:8000/v1/models > evidence/rebench-$UTC/models.json   # DS skill has no doctor.sh; this + containers-before.txt is the readiness record
{ echo "spark1:"; docker ps --format '{{.Names}}\t{{.Image}}\t{{.Status}}'; echo "spark2:"; ssh -o BatchMode=yes spark2 "docker ps --format '{{.Names}}\t{{.Image}}\t{{.Status}}'"; } > evidence/rebench-$UTC/containers-before.txt
.cursor/skills/verify-deepseek-v4-flash-vision/scripts/smoke.sh > evidence/rebench-$UTC/smoke.txt 2>&1; echo exit=$? >> evidence/rebench-$UTC/smoke.txt
python3 smoke_tools.py > evidence/rebench-$UTC/tools.txt 2>&1; echo exit=$? >> evidence/rebench-$UTC/tools.txt
python3 smoke_vision.py > evidence/rebench-$UTC/vision.txt 2>&1; echo exit=$? >> evidence/rebench-$UTC/vision.txt
python3 .cursor/skills/verify-deepseek-v4-flash-vision/scripts/needle_probe.py --prompt-tokens 8000 > evidence/rebench-$UTC/needle-8000.txt 2>&1; echo exit=$? >> evidence/rebench-$UTC/needle-8000.txt
python3 bench_decode.py > evidence/rebench-$UTC/bench.txt 2>&1
# bench.json = the SUMMARY JSON array extracted from bench.txt (python: text[text.rfind("SUMMARY")+7:])
python3 .cursor/skills/verify-deepseek-v4-flash-vision/scripts/needle_probe.py --prompt-tokens 32000 > evidence/rebench-$UTC/needle-32000.txt 2>&1; echo exit=$? >> evidence/rebench-$UTC/needle-32000.txt
python3 .cursor/skills/verify-deepseek-v4-flash-vision/scripts/needle_probe.py --prompt-tokens 120000 > evidence/rebench-$UTC/needle-120000.txt 2>&1; echo exit=$? >> evidence/rebench-$UTC/needle-120000.txt
free -g > evidence/rebench-$UTC/free-after-needles.txt
docker logs --tail 500 dsv4-flash-vision-exp > evidence/rebench-$UTC/engine.log.tail 2>&1
ssh -o BatchMode=yes spark2 docker logs --tail 500 dsv4-flash-vision-exp > evidence/rebench-$UTC/engine-rank1.log.tail 2>&1
docker inspect -f 'rank0 OOMKilled={{.State.OOMKilled}} status={{.State.Status}}' dsv4-flash-vision-exp; ssh spark2 docker inspect -f 'rank1 OOMKilled={{.State.OOMKilled}} status={{.State.Status}}' dsv4-flash-vision-exp
./stop.sh 2>&1 | tee evidence/rebench-$UTC/stop.txt
{ echo "spark1:"; docker ps --format '{{.Names}}\t{{.Image}}\t{{.Status}}'; echo "spark2:"; ssh -o BatchMode=yes spark2 "docker ps --format '{{.Names}}\t{{.Image}}\t{{.Status}}'"; } > evidence/rebench-$UTC/containers-after.txt
~/projects/ai-lab/forge/gpu/lease.sh release pair
